services:

  code:
    image: code
    container_name: code
    build: .
    networks:
      - vaccine
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    build: test/nginx/
    networks:
      - vaccine
    ports:
      - 4646:4646
      - 4343:4343
      - 4444:4444
      - 4545:4545
    restart: always

  mysql:
    image: mysql
    container_name: mysql
    build: test/mysql/
    networks:
      - vaccine
    restart: always

  postgresql:
    image: postgresql
    container_name: postgresql
    build: test/postgresql/
    networks:
      - vaccine
    restart: always

  sqlite:
    image: sqlite
    container_name: sqlite
    build: test/sqlite/
    networks:
      - vaccine
    restart: always

  microsoftsql:
    image: microsoftsql
    container_name: microsoftsql
    build: test/microsoftsql/
    networks:
      - vaccine
    restart: always

networks:

  vaccine:
    driver: bridge
